CC      = gcc
PROF    = 
NOCRYPT = -DNOCRYPT
#Uncomment the next line if you want request support
#DBUGFLG = -DREQUESTS

#I3 - Comment out to disable I3 support
I3 = 1

MCCP = 0

C_FLAGS = -g3 -Wall $(PROF) $(NOCRYPT) $(DBUGFLG)
L_FLAGS = $(PROF) -lz


O_FILES = act_comm.o act_info.o act_move.o act_obj.o act_wiz.o boards.o \
	  build.o clans.o comm.o const.o db.o fight.o \
	  handler.o hashstr.o id.o interp.o magic.o makeobjs.o \
	  misc.o mud_comm.o mud_prog.o player.o requests.o \
	  reset.o save.o shops.o skills.o special.o tables.o track.o update.o \
	  space.o morespace.o swskills.o planets.o vote.o mpxset.o \
	  mxp.o gboard.o webhelp.o


C_FILES = act_comm.c act_info.c act_move.c act_obj.c act_wiz.c boards.c \
	  build.c clans.c comm.c const.c db.c fight.c \
	  handler.c hashstr.c id.c interp.c magic.c makeobjs.c \
	  misc.c mud_comm.c mud_prog.c player.c requests.c \
	  reset.c save.c shops.c skills.c special.c tables.c track.c update.c \
	  space.c morespace.c swskills.c planets.c vote.c mpxset.c \
	  mxp.c gboard.c webhelp.c

H_FILES = mud.h bet.h

ifdef I3
   C_FILES := i3.c $(C_FILES)
   O_FILES := i3.o $(O_FILES)
   C_FLAGS := $(C_FLAGS) -DI3 -DI3SMAUG
endif

ifdef MCCP
   C_FLAGS := $(C_FLAGS) -DMCCP
endif

all:
#	co $(H_FILES)
	make ../bin/swr
#	rm -f $(H_FILES)

../bin/swr: $(O_FILES)
	rm -f ../bin/swr
	$(CC) $(L_FLAGS) -o ../bin/swr $(O_FILES) -lm     # -lcrypt
	chmod g+w ../bin/swr
	chmod g+w $(O_FILES)

.c.o: mud.h
	$(CC) -c $(C_FLAGS) $<

clean:
	rm -f $(O_FILES)
